### ISSUE TITLE
Set scratch space for specific subjects

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/CPP_HPC#27]
Hi, what you said is an important point. But the error that happened to me appeared even with these new numbers. The error was solved by clearing the content in both the output folder and the scratch folder. 
Now in the slurm file I define workdir like this `--work-dir /scratch_dir/work-fmriprep/"${subjID}" \` instead of  `--work-dir /scratch_dir/work-fmriprep \`  to make the scratch folder less likely to be mixed with each others. Does it make sense?

_Originally posted by @yyang1234 in https://github.com/cpp-lln-lab/CPP_HPC/issues/26#issuecomment-1801612747_

**Comment by yyang1234** [comment]
yeah it make sense for me.
